// import path, { resolve } from 'path';
const path = require(`path`)
const fetch = require(`isomorphic-fetch`)
const slugify = require(`slugify`)

async function turnMoviesIntoPages({ graphql, actions }) {
  // 1. Get a template for this page
  const movieTemplate = path.resolve("./src/templates/question.js")
  // 2. Query all Movies
  const response = [
    {
      id: 48001140219,
      type: 1,
      status: 2,
      agent_id: 48048555088,
      created_at: "2020-05-06T12:30:00Z",
      category_id: 48000412653,
      folder_id: 48000607414,
      title: 'What is "Responsive Testing" ?',
      updated_at: "2021-12-20T10:52:45Z",
      description:
        '<p dir="ltr" style="line-height: 1.38; margin-bottom: 0pt;"><span dir="ltr" style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;">Responsive testing is used to check the appearance of a website with RWD(Responsive Web Design).&nbsp;</span></p><p><img src="https://pbs.twimg.com/profile_images/451968255846928384/0pyDMTyp_400x400.png" style="width: 200px; height: 200px;" alt="logo" class="fr-fic fr-dii fr-fil fr-shadow fr-bordered fr-rounded"></p><p dir="ltr" style="line-height: 1.38; margin-bottom: 0pt;"><span dir="ltr" style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;">This design helps a website to render the content in a flexible yet appropriate manner on the basis of the devices &amp; OS on which it gets summoned.</span></p><p><br></p><p><br></p><p><br></p><p><br></p><p><br></p><p><br></p><p><br></p><p><br></p><p><br></p><pre class="fd-callout fd-callout--idea" dir="ltr">Noice</pre><p><br></p><pre class="fd-callout fd-callout--note" dir="ltr">Hola</pre><p><br></p><pre class="fd-callout fd-callout--info" dir="ltr">Hoy</pre><p><br></p><p><br></p><p class="fd-toc"><strong>TABLE OF CONTENTS</strong></p><ul><li dir="ltr">No headings available. Use <strong>Paragraph Format</strong> to add one.</li></ul><p><br></p><hr><p dir="ltr" style="line-height: 1.38; margin-bottom: 0pt;"><span dir="ltr" style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;">We offer desktop browsers and real devices infrastructure for responsive testing.</span></p><table style="width: 100%;"><tbody><tr><td dir="ltr" style="width: 33.3333%;">Hello</td><td dir="ltr" style="width: 33.3333%;">Hi</td><td dir="ltr" style="width: 33.3333%;"><em>Hello</em></td></tr><tr><td dir="ltr" style="width: 33.3333%;">World<br></td><td dir="ltr" style="width: 33.3333%;"><strong>World</strong></td><td dir="ltr" style="width: 33.3333%;">World</td></tr></tbody></table>',
      description_text:
        " Responsive testing is used to check the appearance of a website with RWD(Responsive Web Design).     This design helps a website to render the content in a flexible yet appropriate manner on the basis of the devices & OS on which it gets summoned.                             Noice     Hola     Hoy        TABLE OF CONTENTS   No headings available. Use Paragraph Format to add one.       We offer desktop browsers and real devices infrastructure for responsive testing.  Hello  Hi  Hello  World   World  World ",
      seo_data: {
        meta_title: "",
        meta_description: "",
      },
      tags: [],
      attachments: [
        {
          id: 48171856969,
          name: "240469922_562704495085685_8656723591509602922_n.mp4",
          content_type: "video/mp4",
          size: 1547332,
          created_at: "2021-12-17T12:36:26Z",
          updated_at: "2021-12-17T12:39:44Z",
          attachment_url:
            "https://s3.amazonaws.com/cdn.freshdesk.com/data/helpdesk/attachments/production/48171856969/original/240469922_562704495085685_8656723591509602922_n.mp4?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAS6FNSMY2XLZULJPI%2F20211228%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20211228T181618Z&X-Amz-Expires=300&X-Amz-SignedHeaders=host&X-Amz-Signature=b745984d06e8c3253637bd03aea14cdd3b4adeee00cdf734513adda2b44258d7",
        },
      ],
      cloud_files: [],
      thumbs_up: 0,
      thumbs_down: 0,
      hits: 0,
      suggested: 0,
      feedback_count: 0,
    },
    {
      id: 48001140205,
      type: 1,
      status: 2,
      agent_id: 48014161281,
      created_at: "2020-05-06T12:04:42Z",
      category_id: 48000412653,
      folder_id: 48000607414,
      title: "Blocked countries",
      updated_at: "2021-12-06T09:58:27Z",
      description:
        '<p><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 83, 191); font-weight: 700;">Countries Blocked: Morocco, Mauritania, Sudan, Egypt, Kuwait, Iraq, Yemen, Saudi Arabia, Palestinian Territory, Djibouti, Algeria, Libya, Iran, Oman, Burundi, Somalia, Tunisia, Bangladesh, Jordan, Syrian Arab Republic, Bahrain, Lebanon</span></p>',
      description_text:
        " Countries Blocked: Morocco, Mauritania, Sudan, Egypt, Kuwait, Iraq, Yemen, Saudi Arabia, Palestinian Territory, Djibouti, Algeria, Libya, Iran, Oman, Burundi, Somalia, Tunisia, Bangladesh, Jordan, Syrian Arab Republic, Bahrain, Lebanon ",
      seo_data: {
        meta_title: "",
        meta_description: "",
      },
      tags: ["related"],
      attachments: [],
      cloud_files: [],
      thumbs_up: 0,
      thumbs_down: 0,
      hits: 0,
      suggested: 0,
      feedback_count: 0,
    },
    {
      id: 48001140211,
      type: 1,
      status: 2,
      agent_id: 48009948162,
      created_at: "2020-05-06T12:18:20Z",
      category_id: 48000412653,
      folder_id: 48000607414,
      title:
        "Could you specify what kind of impact the use of BrowserStack licence has on data (privacy) and security (access to testing systems)?",
      updated_at: "2020-05-06T12:33:05Z",
      description:
        '<p dir="ltr" style="line-height: 1.38; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;">Our security policies are outlined here - <a href="https://www.browserstack.com/policy/security.">https://www.browserstack.com/policy/security.</a> </span></p><p dir="ltr" style="line-height: 1.38; margin-bottom: 0pt;"><br></p><p dir="ltr" style="line-height: 1.38; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;">Furthermore, we take security very seriously at BrowserStack and ensure that no user data is cached or stored when testing on BrowserStack\'s remote infrastructure.</span><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;"><br></span><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;"> </span></p><p dir="ltr" style="line-height: 1.38; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;">If there\'s anything specific you are looking for, do share your email address and our Compliance team would reach out to you with more information. You could also reach then directly at compliance@browserstack.com</span></p>',
      description_text:
        " Our security policies are outlined here - https://www.browserstack.com/policy/security.      Furthermore, we take security very seriously at BrowserStack and ensure that no user data is cached or stored when testing on BrowserStack's remote infrastructure.    If there's anything specific you are looking for, do share your email address and our Compliance team would reach out to you with more information. You could also reach then directly at compliance@browserstack.com ",
      seo_data: {
        meta_title: "",
        meta_description: "",
      },
      tags: [],
      attachments: [],
      cloud_files: [],
      thumbs_up: 0,
      thumbs_down: 0,
      hits: 0,
      suggested: 0,
      feedback_count: 0,
    },
    {
      id: 48001140220,
      type: 1,
      status: 2,
      agent_id: 48009948162,
      created_at: "2020-05-06T12:30:35Z",
      category_id: 48000412653,
      folder_id: 48000607414,
      title: "Are the mobile devices real or just emulators?",
      updated_at: "2020-05-06T12:30:35Z",
      description:
        '<p><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;">We offer real mobile devices on our platform and the results are 100% authentic.</span></p>',
      description_text:
        " We offer real mobile devices on our platform and the results are 100% authentic. ",
      seo_data: {
        meta_title: "",
        meta_description: "",
      },
      tags: [],
      attachments: [],
      cloud_files: [],
      thumbs_up: 0,
      thumbs_down: 0,
      hits: 0,
      suggested: 0,
      feedback_count: 0,
    },
    {
      id: 48001140212,
      type: 1,
      status: 2,
      agent_id: 48009948162,
      created_at: "2020-05-06T12:20:55Z",
      category_id: 48000412653,
      folder_id: 48000607414,
      title: "What is BrowserStack or how to Install BrowserStack?",
      updated_at: "2020-05-06T12:33:05Z",
      description:
        '<p dir="ltr" style="line-height: 1.38; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;">BrowserStack is a SAAS (Software As A Service) based tool that can be used to test websites and mobile applications on a range of desktop browser combinations and real mobile devices. </span></p><p dir="ltr" style="line-height: 1.38; margin-bottom: 0pt;"><br></p><p dir="ltr" style="line-height: 1.38; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;">You would be able to access our platform and use the product via your local Chrome browser. </span></p><p dir="ltr" style="line-height: 1.38; margin-bottom: 0pt;"><br></p><p dir="ltr" style="line-height: 1.38; margin-bottom: 0pt;"><br></p><p dir="ltr" style="line-height: 1.38; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;"><a href="https://browserstack">https://browserstack</a>.com</span></p>',
      description_text:
        " BrowserStack is a SAAS (Software As A Service) based tool that can be used to test websites and mobile applications on a range of desktop browser combinations and real mobile devices.      You would be able to access our platform and use the product via your local Chrome browser.         https://browserstack.com ",
      seo_data: {
        meta_title: "",
        meta_description: "",
      },
      tags: [],
      attachments: [],
      cloud_files: [],
      thumbs_up: 0,
      thumbs_down: 0,
      hits: 0,
      suggested: 0,
      feedback_count: 0,
    },
    {
      id: 48001140221,
      type: 1,
      status: 2,
      agent_id: 48009948162,
      created_at: "2020-05-06T12:31:05Z",
      category_id: 48000412653,
      folder_id: 48000607414,
      title: "What are the devices available in a paid plan?",
      updated_at: "2020-05-06T12:31:05Z",
      description:
        '<p><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;">The list of OS browser combinations and mobile devices available across all our products is listed over </span><a href="https://www.browserstack.com/list-of-browsers-and-platforms?product=live"><span style="font-size: 12pt; font-family: Arial; color: rgb(17, 85, 204); font-weight: 400; text-decoration-skip-ink: none;">here</span></a><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;">.</span></p>',
      description_text:
        " The list of OS browser combinations and mobile devices available across all our products is listed over here. ",
      seo_data: {
        meta_title: "",
        meta_description: "",
      },
      tags: [],
      attachments: [],
      cloud_files: [],
      thumbs_up: 0,
      thumbs_down: 0,
      hits: 0,
      suggested: 0,
      feedback_count: 0,
    },
    {
      id: 48001140213,
      type: 1,
      status: 2,
      agent_id: 48009948162,
      created_at: "2020-05-06T12:22:13Z",
      category_id: 48000412653,
      folder_id: 48000607414,
      title: "Is the BrowserStack device the same as a real device?",
      updated_at: "2020-05-06T12:33:05Z",
      description:
        '<p><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;">Yes, we offer physical mobile devices hosted in our data centers across the globe and the results are 100% authentic.</span></p>',
      description_text:
        " Yes, we offer physical mobile devices hosted in our data centers across the globe and the results are 100% authentic. ",
      seo_data: {
        meta_title: "",
        meta_description: "",
      },
      tags: [],
      attachments: [],
      cloud_files: [],
      thumbs_up: 0,
      thumbs_down: 0,
      hits: 0,
      suggested: 0,
      feedback_count: 0,
    },
    {
      id: 48001140215,
      type: 1,
      status: 2,
      agent_id: 48009948162,
      created_at: "2020-05-06T12:23:14Z",
      category_id: 48000412653,
      folder_id: 48000607414,
      title:
        "So is there anything which I can do to run browser stack smoothly?",
      updated_at: "2020-05-06T12:33:05Z",
      description:
        '<p><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;">For optimal testing performance, we suggest all our users access BrowserStack via Chrome on their local machine and with a network with a minimum speed of 4-5 Mbps.</span></p>',
      description_text:
        " For optimal testing performance, we suggest all our users access BrowserStack via Chrome on their local machine and with a network with a minimum speed of 4-5 Mbps. ",
      seo_data: {
        meta_title: "",
        meta_description: "",
      },
      tags: [],
      attachments: [],
      cloud_files: [],
      thumbs_up: 0,
      thumbs_down: 0,
      hits: 0,
      suggested: 0,
      feedback_count: 0,
    },
    {
      id: 48001140216,
      type: 1,
      status: 2,
      agent_id: 48009948162,
      created_at: "2020-05-06T12:24:36Z",
      category_id: 48000412653,
      folder_id: 48000607414,
      title: "Does BrowserStack support ChromeOS?",
      updated_at: "2020-05-19T03:43:29Z",
      description:
        '<p data-identifyelement="458"><span data-identifyelement="459" style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;">Support for ChromeOS is unavailable on our platform at the moment. </span></p><p data-identifyelement="460"><br data-identifyelement="461"></p><p data-identifyelement="462"><span data-identifyelement="463" style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;">Having said that, your requirement will definitely be shared with the product team.</span></p><p data-identifyelement="462"><br></p>',
      description_text:
        " Support for ChromeOS is unavailable on our platform at the moment.      Having said that, your requirement will definitely be shared with the product team.    ",
      seo_data: {
        meta_title: "",
        meta_description: "",
      },
      tags: [],
      attachments: [],
      cloud_files: [],
      thumbs_up: 0,
      thumbs_down: 0,
      hits: 0,
      suggested: 0,
      feedback_count: 0,
    },
    {
      id: 48001140218,
      type: 1,
      status: 2,
      agent_id: 48009948162,
      created_at: "2020-05-06T12:28:42Z",
      category_id: 48000412653,
      folder_id: 48000607414,
      title:
        "Can't access any browser/I can not run any device/connection error",
      updated_at: "2020-05-06T12:32:40Z",
      description:
        '<p dir="ltr" style="line-height: 1.38; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;">It seems that you are accessing BrowserStack via &lt;Country&gt;. We have recently blocked access to our platform for free trial users from &lt;Country&gt; due to continuous spamming.</span><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;"><br><br></span></p><p dir="ltr" style="line-height: 1.38; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;">With that being said, you should be able to launch remote browsers without any issues with a paid subscription.</span></p>',
      description_text:
        " It seems that you are accessing BrowserStack via <Country>. We have recently blocked access to our platform for free trial users from <Country> due to continuous spamming.    With that being said, you should be able to launch remote browsers without any issues with a paid subscription. ",
      seo_data: {
        meta_title: "",
        meta_description: "",
      },
      tags: [],
      attachments: [],
      cloud_files: [],
      thumbs_up: 0,
      thumbs_down: 0,
      hits: 0,
      suggested: 0,
      feedback_count: 0,
    },
    {
      id: 48001140224,
      type: 1,
      status: 2,
      agent_id: 48009948162,
      created_at: "2020-05-06T12:33:31Z",
      category_id: 48000412653,
      folder_id: 48000607414,
      title:
        "What is the difference between a real device and simulated device?",
      updated_at: "2020-05-06T12:33:31Z",
      description:
        '<p dir="ltr" style="line-height: 1.38; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;">Real devices offer native experience and actual behavior. Simulators, on the other hand, are less reliable since they do not represent real-world conditions and are basically using the machine\'s hardware. </span></p><p><br></p><p><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;">Here is a detailed comparison - </span><a href="https://www.browserstack.com/guide/testing-on-emulators-simulators-real-devices-comparison"><span style="font-size: 12pt; font-family: Arial; color: rgb(17, 85, 204); font-weight: 400; text-decoration-skip-ink: none;">https://www.browserstack.com/guide/testing-on-emulators-simulators-real-devices-comparison</span></a></p>',
      description_text:
        " Real devices offer native experience and actual behavior. Simulators, on the other hand, are less reliable since they do not represent real-world conditions and are basically using the machine's hardware.      Here is a detailed comparison - https://www.browserstack.com/guide/testing-on-emulators-simulators-real-devices-comparison ",
      seo_data: {
        meta_title: "",
        meta_description: "",
      },
      tags: [],
      attachments: [],
      cloud_files: [],
      thumbs_up: 0,
      thumbs_down: 0,
      hits: 0,
      suggested: 0,
      feedback_count: 0,
    },
    {
      id: 48001140225,
      type: 1,
      status: 2,
      agent_id: 48009948162,
      created_at: "2020-05-06T12:34:48Z",
      category_id: 48000412653,
      folder_id: 48000607414,
      title: "Does BrowserStack support audio?",
      updated_at: "2020-05-06T12:34:48Z",
      description:
        '<p dir="ltr" style="line-height: 1.38; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;">Support for audio is available on all our desktop browsers (except macOS Mojave and Catalina) at the moment.</span></p><p><br></p><p dir="ltr" style="line-height: 1.38; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;">Furthermore, adding support for audio on mobile devices is on our long term roadmap and you will be notified with the updates.</span></p>',
      description_text:
        " Support for audio is available on all our desktop browsers (except macOS Mojave and Catalina) at the moment.     Furthermore, adding support for audio on mobile devices is on our long term roadmap and you will be notified with the updates. ",
      seo_data: {
        meta_title: "",
        meta_description: "",
      },
      tags: [],
      attachments: [],
      cloud_files: [],
      thumbs_up: 0,
      thumbs_down: 0,
      hits: 0,
      suggested: 0,
      feedback_count: 0,
    },
    {
      id: 48001140226,
      type: 1,
      status: 2,
      agent_id: 48009948162,
      created_at: "2020-05-06T12:35:21Z",
      category_id: 48000412653,
      folder_id: 48000607414,
      title: "Are you able to provide 25.000 or more simultaneous connections?",
      updated_at: "2020-05-06T12:35:21Z",
      description:
        '<p><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;">I believe you are referring to performance testing which is currently not supported.</span></p>',
      description_text:
        " I believe you are referring to performance testing which is currently not supported. ",
      seo_data: {
        meta_title: "",
        meta_description: "",
      },
      tags: [],
      attachments: [],
      cloud_files: [],
      thumbs_up: 0,
      thumbs_down: 0,
      hits: 0,
      suggested: 0,
      feedback_count: 0,
    },
    {
      id: 48001140228,
      type: 1,
      status: 2,
      agent_id: 48009948162,
      created_at: "2020-05-06T12:36:13Z",
      category_id: 48000412653,
      folder_id: 48000607414,
      title: "Does BrowserStack offer performance testing?",
      updated_at: "2020-05-06T12:36:20Z",
      description:
        '<p><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;">We do not offer performance testing services yet.</span></p>',
      description_text: " We do not offer performance testing services yet. ",
      seo_data: {
        meta_title: "",
        meta_description: "",
      },
      tags: [],
      attachments: [],
      cloud_files: [],
      thumbs_up: 0,
      thumbs_down: 0,
      hits: 0,
      suggested: 0,
      feedback_count: 0,
    },
    {
      id: 48001140229,
      type: 1,
      status: 2,
      agent_id: 48009948162,
      created_at: "2020-05-06T12:39:01Z",
      category_id: 48000412653,
      folder_id: 48000607414,
      title: "Does BrowserStack provides support for linux?",
      updated_at: "2020-05-06T12:39:09Z",
      description:
        '<p><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;">Support for Linux distributions is unavailable on our platform at the moment. </span></p><p><br></p><p><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;">Having said that, your requirements have been shared with the product team and we will make sure that you are notified of any further updates.</span></p>',
      description_text:
        " Support for Linux distributions is unavailable on our platform at the moment.      Having said that, your requirements have been shared with the product team and we will make sure that you are notified of any further updates. ",
      seo_data: {
        meta_title: "",
        meta_description: "",
      },
      tags: [],
      attachments: [],
      cloud_files: [],
      thumbs_up: 0,
      thumbs_down: 0,
      hits: 0,
      suggested: 0,
      feedback_count: 0,
    },
    {
      id: 48001140230,
      type: 1,
      status: 2,
      agent_id: 48009948162,
      created_at: "2020-05-06T12:39:59Z",
      category_id: 48000412653,
      folder_id: 48000607414,
      title:
        "I want to change resolution / or screen size - do such configurations exist?",
      updated_at: "2020-05-06T12:40:08Z",
      description:
        '<p><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;">You will be unable to change the resolution or screen size while testing with our real mobile devices. </span></p><p><br></p><p><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;">However, we do offer functionality to test different resolutions with our desktop browsers.</span></p>',
      description_text:
        " You will be unable to change the resolution or screen size while testing with our real mobile devices.      However, we do offer functionality to test different resolutions with our desktop browsers. ",
      seo_data: {
        meta_title: "",
        meta_description: "",
      },
      tags: [],
      attachments: [],
      cloud_files: [],
      thumbs_up: 0,
      thumbs_down: 0,
      hits: 0,
      suggested: 0,
      feedback_count: 0,
    },
    {
      id: 48001140231,
      type: 1,
      status: 2,
      agent_id: 48009948162,
      created_at: "2020-05-06T12:41:25Z",
      category_id: 48000412653,
      folder_id: 48000607414,
      title: "Having issues where on safari. Getting a certificate error.",
      updated_at: "2020-05-06T12:41:34Z",
      description:
        '<p><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;">It seems that your testing environment is using a self-signed/custom SSL certificate that is not globally trusted. </span></p><p><br></p><p><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;">Furthermore, installing custom SSL certificates on BrowserStack\'s remote infrastructure is not supported due to security reasons. </span><br><br></p><p><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;">You could simply bypass the SSL errors and continue testing. </span></p>',
      description_text:
        " It seems that your testing environment is using a self-signed/custom SSL certificate that is not globally trusted.      Furthermore, installing custom SSL certificates on BrowserStack's remote infrastructure is not supported due to security reasons.     You could simply bypass the SSL errors and continue testing.  ",
      seo_data: {
        meta_title: "",
        meta_description: "",
      },
      tags: [],
      attachments: [],
      cloud_files: [],
      thumbs_up: 0,
      thumbs_down: 0,
      hits: 0,
      suggested: 0,
      feedback_count: 0,
    },
    {
      id: 48001140237,
      type: 1,
      status: 2,
      agent_id: 48009948162,
      created_at: "2020-05-06T13:17:51Z",
      category_id: 48000412653,
      folder_id: 48000607414,
      title: "How to launch a BrowserStack browser with command line flags",
      updated_at: "2020-05-06T13:17:51Z",
      description:
        '<p><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;">Unfortunately, it is not possible to launch the browser with any CLI flags, on BrowserStack</span></p>',
      description_text:
        " Unfortunately, it is not possible to launch the browser with any CLI flags, on BrowserStack ",
      seo_data: {
        meta_title: "",
        meta_description: "",
      },
      tags: [],
      attachments: [],
      cloud_files: [],
      thumbs_up: 0,
      thumbs_down: 0,
      hits: 0,
      suggested: 0,
      feedback_count: 0,
    },
    {
      id: 48001140243,
      type: 1,
      status: 2,
      agent_id: 48009948162,
      created_at: "2020-05-06T13:25:10Z",
      category_id: 48000412653,
      folder_id: 48000607414,
      title: "How to check devices in dark mode?",
      updated_at: "2020-05-06T13:25:10Z",
      description:
        '<p><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;">Support for testing with the dark mode functionality is unavailable on our platform at the moment.</span><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;"><br></span><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;"><br></span><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;">Having said that, your requirements have been shared with the product team. We will keep you posted on any progress on this front.</span></p>',
      description_text:
        " Support for testing with the dark mode functionality is unavailable on our platform at the moment.  Having said that, your requirements have been shared with the product team. We will keep you posted on any progress on this front. ",
      seo_data: {
        meta_title: "",
        meta_description: "",
      },
      tags: [],
      attachments: [],
      cloud_files: [],
      thumbs_up: 0,
      thumbs_down: 0,
      hits: 0,
      suggested: 0,
      feedback_count: 0,
    },
    {
      id: 48001140244,
      type: 1,
      status: 2,
      agent_id: 48009948162,
      created_at: "2020-05-06T13:25:41Z",
      category_id: 48000412653,
      folder_id: 48000607414,
      title: "What browsers should I use to access BrowserStack?",
      updated_at: "2020-05-06T13:25:41Z",
      description:
        '<p><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;">For optimal testing experience, we suggest accessing BrowserStack via Chrome on a local machine.</span></p>',
      description_text:
        " For optimal testing experience, we suggest accessing BrowserStack via Chrome on a local machine. ",
      seo_data: {
        meta_title: "",
        meta_description: "",
      },
      tags: [],
      attachments: [],
      cloud_files: [],
      thumbs_up: 0,
      thumbs_down: 0,
      hits: 0,
      suggested: 0,
      feedback_count: 0,
    },
    {
      id: 48001140245,
      type: 1,
      status: 2,
      agent_id: 48009948162,
      created_at: "2020-05-06T13:26:57Z",
      category_id: 48000412653,
      folder_id: 48000607414,
      title: "I need to test on foldable phones?",
      updated_at: "2020-05-06T13:26:57Z",
      description:
        '<p><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;">Support for testing on foldable phones is unavailable on our platform at the moment. </span></p><p><br></p><p><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;">Having said that, your requirements have been with the product team. We will keep you posted on any progress on this front.</span></p>',
      description_text:
        " Support for testing on foldable phones is unavailable on our platform at the moment.      Having said that, your requirements have been with the product team. We will keep you posted on any progress on this front. ",
      seo_data: {
        meta_title: "",
        meta_description: "",
      },
      tags: [],
      attachments: [],
      cloud_files: [],
      thumbs_up: 0,
      thumbs_down: 0,
      hits: 0,
      suggested: 0,
      feedback_count: 0,
    },
    {
      id: 48001140247,
      type: 1,
      status: 2,
      agent_id: 48009948162,
      created_at: "2020-05-06T13:28:53Z",
      category_id: 48000412653,
      folder_id: 48000607414,
      title:
        "Does your logo pop up in any case while capturing screenshots using the inbuilt function in BrowserStack ‘App Live’?",
      updated_at: "2020-05-06T13:28:53Z",
      description:
        '<p dir="ltr" style="line-height: 1.38; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;">The logo won\'t be visible while capturing screenshots for the mobile application on BrowserStack \'App Live\'</span></p>',
      description_text:
        " The logo won't be visible while capturing screenshots for the mobile application on BrowserStack 'App Live' ",
      seo_data: {
        meta_title: "",
        meta_description: "",
      },
      tags: [],
      attachments: [],
      cloud_files: [],
      thumbs_up: 0,
      thumbs_down: 0,
      hits: 0,
      suggested: 0,
      feedback_count: 0,
    },
    {
      id: 48001140256,
      type: 1,
      status: 2,
      agent_id: 48009948162,
      created_at: "2020-05-06T14:24:29Z",
      category_id: 48000412653,
      folder_id: 48000607414,
      title: "Is there any way to test for different monitor color settings?",
      updated_at: "2020-05-06T14:24:29Z",
      description:
        '<p><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;">We, currently, do not offer the functionality to test websites with different monitor color settings on BrowserStack.</span></p>',
      description_text:
        " We, currently, do not offer the functionality to test websites with different monitor color settings on BrowserStack. ",
      seo_data: {
        meta_title: "",
        meta_description: "",
      },
      tags: [],
      attachments: [],
      cloud_files: [],
      thumbs_up: 0,
      thumbs_down: 0,
      hits: 0,
      suggested: 0,
      feedback_count: 0,
    },
    {
      id: 48001140259,
      type: 1,
      status: 2,
      agent_id: 48009948162,
      created_at: "2020-05-06T14:26:38Z",
      category_id: 48000412653,
      folder_id: 48000607414,
      title: "Is there a way to test apple pay connections on BrowserStack?",
      updated_at: "2020-05-06T14:26:38Z",
      description:
        '<p><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;">The functionality to test the Apple Pay functionality is, c<span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;">urrently, </span>unavailable on BrowserStack. </span></p><p><br></p><p><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;">However, this has been taken as a product feature request and you will be notified should there be any developments on that front.</span></p>',
      description_text:
        " The functionality to test the Apple Pay functionality is, currently, unavailable on BrowserStack.      However, this has been taken as a product feature request and you will be notified should there be any developments on that front. ",
      seo_data: {
        meta_title: "",
        meta_description: "",
      },
      tags: [],
      attachments: [],
      cloud_files: [],
      thumbs_up: 0,
      thumbs_down: 0,
      hits: 0,
      suggested: 0,
      feedback_count: 0,
    },
    {
      id: 48001140260,
      type: 1,
      status: 2,
      agent_id: 48009948162,
      created_at: "2020-05-06T14:27:32Z",
      category_id: 48000412653,
      folder_id: 48000607414,
      title: "How to test  whether a bluetooth device is connected or not?",
      updated_at: "2020-05-06T14:27:32Z",
      description:
        '<p><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;">Support for testing Bluetooth connectivity between multiple devices available on BrowserStack is unavailable at the moment.</span></p>',
      description_text:
        " Support for testing Bluetooth connectivity between multiple devices available on BrowserStack is unavailable at the moment. ",
      seo_data: {
        meta_title: "",
        meta_description: "",
      },
      tags: [],
      attachments: [],
      cloud_files: [],
      thumbs_up: 0,
      thumbs_down: 0,
      hits: 0,
      suggested: 0,
      feedback_count: 0,
    },
    {
      id: 48001140262,
      type: 1,
      status: 2,
      agent_id: 48009948162,
      created_at: "2020-05-06T14:30:28Z",
      category_id: 48000412653,
      folder_id: 48000607414,
      title: "Does BrowserStack offer Surface Go/Surface Pro for testing?",
      updated_at: "2020-05-06T14:30:28Z",
      description:
        '<p dir="ltr" style="line-height: 1.38; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;">Support for testing on Surface Go devices is currently unavailable on BrowserStack.</span></p><p dir="ltr" style="line-height: 1.38; margin-bottom: 0pt;"><br></p><p dir="ltr" style="line-height: 1.38; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;">However, this has been taken as a feature request and we will make sure to notify you of any progress on this front.</span></p>',
      description_text:
        " Support for testing on Surface Go devices is currently unavailable on BrowserStack.     However, this has been taken as a feature request and we will make sure to notify you of any progress on this front. ",
      seo_data: {
        meta_title: "",
        meta_description: "",
      },
      tags: [],
      attachments: [],
      cloud_files: [],
      thumbs_up: 0,
      thumbs_down: 0,
      hits: 0,
      suggested: 0,
      feedback_count: 0,
    },
    {
      id: 48001140264,
      type: 1,
      status: 2,
      agent_id: 48009948162,
      created_at: "2020-05-06T14:34:33Z",
      category_id: 48000412653,
      folder_id: 48000607414,
      title:
        "Does BrowserStack support testing on Samsung Galaxy Tab A devices?",
      updated_at: "2020-05-06T14:34:33Z",
      description:
        '<p><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;">Support for Samsung Galaxy Tab A is currently unavailable on BrowserStack.</span></p><p><br></p><p><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;">However, this has been taken as a feature request and shared with the Product team. We will make sure to notify you as soon as there is any progress on this front.</span></p><p><br></p>',
      description_text:
        " Support for Samsung Galaxy Tab A is currently unavailable on BrowserStack.     However, this has been taken as a feature request and shared with the Product team. We will make sure to notify you as soon as there is any progress on this front.    ",
      seo_data: {
        meta_title: "",
        meta_description: "",
      },
      tags: [],
      attachments: [],
      cloud_files: [],
      thumbs_up: 0,
      thumbs_down: 0,
      hits: 0,
      suggested: 0,
      feedback_count: 0,
    },
    {
      id: 48001140266,
      type: 1,
      status: 2,
      agent_id: 48009948162,
      created_at: "2020-05-06T14:35:33Z",
      category_id: 48000412653,
      folder_id: 48000607414,
      title: "Does BrowserStack support testing on Odys Thanos 10 devices?",
      updated_at: "2020-05-06T14:35:33Z",
      description:
        '<p><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;">Support for <span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;">Odys Thanos 10</span> is currently unavailable on BrowserStack.</span></p><p><br></p><p><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;">However, this has been taken as a feature request and shared with the Product team. We will make sure to notify you as soon as there is any progress on this front.</span></p><p><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;"></span><br></p>',
      description_text:
        " Support for Odys Thanos 10 is currently unavailable on BrowserStack.     However, this has been taken as a feature request and shared with the Product team. We will make sure to notify you as soon as there is any progress on this front.    ",
      seo_data: {
        meta_title: "",
        meta_description: "",
      },
      tags: [],
      attachments: [],
      cloud_files: [],
      thumbs_up: 0,
      thumbs_down: 0,
      hits: 0,
      suggested: 0,
      feedback_count: 0,
    },
    {
      id: 48001140272,
      type: 1,
      status: 2,
      agent_id: 48009948162,
      created_at: "2020-05-06T15:00:12Z",
      category_id: 48000412653,
      folder_id: 48000607414,
      title: "Does BrowserStack support testing on Realme devices?",
      updated_at: "2020-05-06T15:00:12Z",
      description:
        '<p><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;">Support for <span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;">Realme device</span>s is currently unavailable on BrowserStack.</span></p><p><br></p><p><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;">However, this has been taken as a feature request and shared with the Product team. We will make sure to notify you as soon as there is any progress on this front.</span></p><p><br></p><p><br></p>',
      description_text:
        " Support for Realme devices is currently unavailable on BrowserStack.     However, this has been taken as a feature request and shared with the Product team. We will make sure to notify you as soon as there is any progress on this front.       ",
      seo_data: {
        meta_title: "",
        meta_description: "",
      },
      tags: [],
      attachments: [],
      cloud_files: [],
      thumbs_up: 0,
      thumbs_down: 0,
      hits: 0,
      suggested: 0,
      feedback_count: 0,
    },
    {
      id: 48001140274,
      type: 1,
      status: 2,
      agent_id: 48009948162,
      created_at: "2020-05-06T15:02:24Z",
      category_id: 48000412653,
      folder_id: 48000607414,
      title: "​Does BrowserStack support testing on Oneplus 6 devices?",
      updated_at: "2020-05-06T15:02:24Z",
      description:
        '<p><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;">Support for <span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;">Oneplus 6 device</span>s is currently unavailable on BrowserStack.</span></p><p><br></p><p><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;">However, this has been taken as a feature request and shared with the Product team. We will make sure to notify you as soon as there is any progress on this front.</span></p><p><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;"><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400;"></span></span><br></p>',
      description_text:
        " Support for Oneplus 6 devices is currently unavailable on BrowserStack.     However, this has been taken as a feature request and shared with the Product team. We will make sure to notify you as soon as there is any progress on this front.    ",
      seo_data: {
        meta_title: "",
        meta_description: "",
      },
      tags: [],
      attachments: [],
      cloud_files: [],
      thumbs_up: 0,
      thumbs_down: 0,
      hits: 0,
      suggested: 0,
      feedback_count: 0,
    },
  ]

  console.log("*****", response)
  // const movies = await response.json()
  // 3. Loop over each movie and create a page for that movie
  response.forEach(movie => {
    actions.createPage({
      path: `questions/${movie.id}`,
      component: movieTemplate,
      context: {
        title: movie.title,
        description_text: movie.description,
      },
    })
  })
}

exports.createPages = async params => {
  // Create pages dynamically
  await Promise.all([turnMoviesIntoPages(params)])
}
